version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:symfony-dev-${CONTAINER_ORCHESTRATION_TAG_VERSION}
        env_file:
            - .env
        volumes:
            - $PWD/:/var/www/app
