<?php

/*
 * This file is autogenerated at 08/05/2016 4:02pm by gpupo/common-sdk
 * @see <http://www.g1mr.com/common-sdk/>
 */

namespace ;

use Gpupo\CommonSdk\Entity\EntityInterface;
use Gpupo\Tests\CommonSdk\Traits\EntityTrait;
use ;
use Gpupo\ShippingServices\Factory;

/**
 * @coversDefaultClass \Gpupo\ShippingServices\Factory
 *
 *
 */
class FactoryTest extends TestCaseAbstract
{

    /**
     * @return \Gpupo\ShippingServices\Factory
     */
    public function dataProviderFactory()
    {
        return [[new Factory()]];
    }
        
    /**
     * @testdox ``setClient()``
     * @cover ::setClient
     * @dataProvider dataProviderFactory
     * @test
     */
    public function setClient(Factory $factory)
    {
        $this->markIncomplete('setClient() need implementation!');
    }
    
    /**
     * @testdox ``getNamespace()``
     * @cover ::getNamespace
     * @dataProvider dataProviderFactory
     * @test
     */
    public function getNamespace(Factory $factory)
    {
        $this->markIncomplete('getNamespace() need implementation!');
    }
    
    /**
     * @testdox ``getSchema()``
     * @cover ::getSchema
     * @dataProvider dataProviderFactory
     * @test
     */
    public function getSchema(Factory $factory)
    {
        $this->markIncomplete('getSchema() need implementation!');
    }
}
